<?php
namespace app\index\controller;


use think\Controller;
use think\Db;
use think\Request;

class Index extends Controller
{
    private $type;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->type = Db::name('type')->where('sts>0')->select();

    }

    public function index()
    {
        $list = Db::name("foods")
            ->alias('f')
            ->join("eo_type t","f.t_id=t.id","left")
            ->field('f.id,f.name,f.thumb')
            ->order('f.insert_time')
            ->where("f.sts",'>',0)
            ->where("t.sts",'>',0)
            ->paginate(10);
        $page = $list->render();
        return $this->fetch('index',array('type'=>$this->type,'page'=>$page,'list'=>$list));
    }
    public function type($type)
    {
//        $type = $request->request('type');
//        $list = Db::query('select f.id,f.name from eo_foods f LEFT JOIN eo_type t ON f.t_id = t.id where f.sts > 0');
        $list = Db::name("foods")
            ->alias('f')
            ->join("eo_type t","f.t_id=t.id","left")
            ->field('f.id,f.name,f.thumb')
            ->where("f.t_id",$type)
            ->where("f.sts",'>',0)
            ->where("t.sts",'>',0)
            ->paginate(10);
//        dump($list);
        // 查询状态为1的用户数据 并且每页显示10条数据
//        $list = Db::name('foods')->where(array('sts'=>['>',0],'id'=>$type))->paginate(10);
        // 获取分页显示
        $page = $list->render();
        return $this->fetch('index/list',array('type'=>$this->type,'page'=>$page,'list'=>$list));
    }
    public function receive()
    {
        return json($_POST);
    }
}
