<?php
namespace app\index\controller;


use think\Controller;
use think\Db;
use think\Request;

class Index extends Controller
{
    private $type;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->type = Db::name('type')->where('sts>0')->select();

    }

    public function index()
    {
        return $this->fetch('index',array('active'=>'index'));
    }
    public function type($type)
    {
//        $type = $request->request('type');
//        $list = Db::query('select f.id,f.name from eo_foods f LEFT JOIN eo_type t ON f.t_id = t.id where f.sts > 0');
        $list = Db::name("foods")
            ->alias('f')
            ->join("eo_type t","f.t_id=t.id","left")
            ->field('f.id,f.name,f.thumb')
            ->where("f.t_id",$type)
            ->where("f.sts",'>',0)
            ->where("t.sts",'>',0)
            ->paginate(10);
//        dump($list);
        // 查询状态为1的用户数据 并且每页显示10条数据
//        $list = Db::name('foods')->where(array('sts'=>['>',0],'id'=>$type))->paginate(10);
        // 获取分页显示
        $page = $list->render();
        return $this->fetch('index/list',array('type'=>$this->type,'page'=>$page,'list'=>$list));
    }
    public function product(Request $request)
    {
        $param = $request->request();
        $id = isset($param['id']) ? $param['id'] : 1;
        $list = Db::name("foods")
            ->alias('f')
            ->join("eo_type t","f.t_id=t.id","left")
            ->field('f.id,f.name,f.thumb')
            ->order('f.insert_time')
            ->where("f.sts",'>',0)
            ->where("t.sts",'>',0)
            ->where('f.t_id',$id)
//            ->limit(0,10)
            ->select();
        // 渲染模板输出
        return $this->fetch('index/product',array('type'=>$this->type,'list'=>$list,'active'=>'product'));
    }
    public function find(Request $request)
    {
        // 获取客户端提交的数据
        $param =  $request->request();
        if (!isset($param['id'])) {
            return json(array('code'=>103,'msg'=>'参数不正确'));
        }
        $page = isset($param['page']) ? $param['page'] : 1;
        $foods = Db::name('foods');
        $total = $foods->where('t_id',$param['id'])->count('id');
        $pageSize = 20;
        $totalPage = $total === 0 ? $total : ceil($total/$pageSize);
        $start = $page == 1 ? 0 : ($page-1)*$total;
        $list = $foods->alias('f')
            ->join('eo_type t','f.t_id = t.id','LEFT')
            ->field('f.id,f.name,f.thumb')
            ->where('t.sts','>',0)
            ->where('f.sts','>',0)
            ->where('f.t_id',$param['id'])
            ->limit($start,$pageSize)
            ->select();
        if ($list !== null) {
            return json(
                array(
                    'code'=>200,
                    'msg'=>'查询成功',
                    'totalPage'=>$totalPage,
                    'data'=>['list'=>$list]
                )
            );
        }
        return json(
            array(
                'code'=>109,
                'msg'=>'查询失败',
                'data'=>['list'=>$list]
            )
        );

    }
    public function about()
    {
        return $this->fetch('index/about',array('active'=>'about'));
    }
    public function concat()
    {
        return $this->fetch('index/concat',array('active'=>'concat'));
    }
}
